baseURL = 'http://gitbom.dev/'
languageCode = 'en-us'
title = 'GitBOM'

[module]
  [[module.imports]]
    path = "github.com/FortAwesome/Font-Awesome"
  [[module.imports.mounts]]
    source = "scss"
    target = "assets/sass/fontawesome"
  [[module.imports.mounts]]
    source = "webfonts"
    target = "static/webfonts"

  [[module.imports]]
    path="github.com/jgthms/bulma"
  [[module.imports.mounts]]
    source = "."
    target = "assets/sass/bulma"

  [[module.imports]]
    path="github.com/twbs/bootstrap"
  [[module.imports.mounts]]
    source = "dist/css"
    target = "assets/css/bootstrap"
  [[module.imports.mounts]]
    source = "dist/js"
    target = "static/js/bootstrap"

  [[module.imports]]
    path="github.com/jquery/jquery"
  [[module.imports.mounts]]
    source = "dist"
    target = "static/js/jquery"

  [[module.imports]]
    path="github.com/mermaid-js/mermaid"
  [[module.imports.mounts]]
    source = "dist"
    target = "static/js/mermaid"

# Syntax highlighting settings
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
    [markup.goldmark.parser]
      [markup.goldmark.parser.attribute]
        block = true
        title = true
  [markup.highlight]
    lineNos = true
    lineNumbersInTable = true
    noClasses = false
    style = 'monokailight'
  [markup.tableOfContents]
    endLevel = 3
    ordered = false
    startLevel = 1

[params]
subtitle = 'Automatic and Verifiable Artifact Resolution'
fontawesomeversion = "5.8.1"
[[params.fonts]]
name = "Nunito Sans"
sizes = [300, 400, 600, 700]
type = "sans_serif"

[[params.fonts]]
name = "Roboto Mono"
sizes = [300, 400, 600, 700]
type = "monospace"

[params.social]
    github = "https://github.com/gitbom/"
    twitter = "https://twitter.com/gitbom"

[params.logos]
navbar = "gitbom-logo.svg"
hero = "gitbom-logo.svg"

[menu]
[[menu.navbar]]
name = "Resources"
url = "/resources/"
weight = 1
[[menu.navbar]]
name = "Community"
url = "/community/"
weight = 2